version: "3.8"

services:
  # =====================================
  # 1. OLLAMA (thay cho vLLM)
  # =====================================
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  # =====================================
  # 2. KONG DATABASE
  # =====================================
  kong-db:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    volumes:
      - kong_db:/var/lib/postgresql/data
    restart: always

  # =====================================
  # 3. KONG GATEWAY
  # =====================================
  kong:
    image: kong:3.2
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    restart: always

  # =====================================
  # 4. PROMETHEUS
  # =====================================
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - ollama
      - kong

  # =====================================
  # 5. GRAFANA
  # =====================================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus 
    restart: unless-stopped

  ollama-exporter:
    image: lucabecker42/ollama-exporter:1.0.1
    environment:
      OLLAMA_URL: http://ollama:11434
    ports:
      - "9178:9178"
    depends_on:
      - ollama


volumes:
  kong_db:
  ollama_data:
  grafana_data: