global:
  scrape_interval: 5s

scrape_configs:
  - job_name: kong
    metrics_path: /metrics
    static_configs:
      - targets: ["kong:8001"]

  - job_name: ollama
    static_configs:
      - targets: ["ollama-exporter:8000"]
